project:
  type: website

editor: 
  render-on-save: true

execute:
  freeze: auto
  warning: false     # Hides annoying Python/package package warnings
  message: false     # Hides package startup messages

# master list of allowed blog categories
blog:
  categories:
    - Weeknotes
    - Research
    - TESSERA
    - Maps
    - Birds
    - Gardening
    - Books
    - Papers
    - Code
    - Conservation
    - Ecology
    - KBAs
    - SDM



website:
  title: "Aneesh Naik"
  description: "Personal webpage and blog of Aneesh Naik."
  site-url: "https://www.aneeshnaik.com/"
  navbar:
    logo: assets/AneeshNaikCropped.jpg
    left:
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
  page-footer:
    left: © 2026 Aneesh Naik. Site built with [Quarto](https://quarto.org/).
    right: |
      Find me out in the wild: &nbsp;
      [{{< fa brands github >}}](https://github.com/aneeshnaik) &nbsp;
      [{{< fa brands linkedin >}}](https://linkedin.com/in/aneesh-naik-2030191a5) &nbsp;
      [{{< fa brands orcid >}}](https://orcid.org/0000-0001-6841-1496)

format:
  html:
    theme: cosmo
    reference-location: margin
    mainfont: "EB Garamond"
    css: styles.css
    toc: false
    cap-location: margin
    link-external-newwindow: true
    link-external-icon: true
